name: CI (iOS)

on:
  push:
    branches: [ main ]
    paths:
      - 'iOS/**'
      - '.swiftlint.yml'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'iOS/**'
      - '.swiftlint.yml'
      - '.github/workflows/ci.yml'

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    container: ghcr.io/realm/swiftlint:0.57.0
    steps:
      - uses: actions/checkout@v4
      - name: Run SwiftLint
        run: swiftlint lint --reporter github-actions-logging
